[package]
name = "streamdb"
version = "0.1.0"
authors = ["msherer <msherer95@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "src/warehouse",
    "src/utils"
]

[dependencies]
warehouse = { path = "src/warehouse" }
